DEBUG 2020-10-13 06:01:23.238 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-13 06:01:23.239 UTC: 	 Running on: Linux lxplus787.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-13 06:01:23.239 UTC: 	 Executing command: 'status'
DEBUG 2020-10-13 06:01:23.240 UTC: 	 Found CRAB cache file /afs/cern.ch/user/c/choij/.crab3
ERROR 2020-10-13 06:01:23.245 UTC: 	 Error: crab_DYJetsToLL_mg271_amcatnlo-pythia8/ is not a valid CRAB project directory.
ERROR 2020-10-13 06:01:23.245 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 623, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_DYJetsToLL_mg271_amcatnlo-pythia8/ is not a valid CRAB project directory.
INFO 2020-10-13 06:01:23.253 UTC: 	 Log file is /eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DY_012j_MGNLO_v271/crab.log
DEBUG 2020-10-13 07:49:18.667 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-13 07:49:18.667 UTC: 	 Running on: Linux lxplus787.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-13 07:49:18.667 UTC: 	 Executing command: 'status'
DEBUG 2020-10-13 07:49:18.668 UTC: 	 Found CRAB cache file /afs/cern.ch/user/c/choij/.crab3
ERROR 2020-10-13 07:49:18.670 UTC: 	 Error: crab_DYJetsToLL_mg271_amcatnlo-pythia8/ is not a valid CRAB project directory.
ERROR 2020-10-13 07:49:18.670 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 623, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_DYJetsToLL_mg271_amcatnlo-pythia8/ is not a valid CRAB project directory.
INFO 2020-10-13 07:49:18.678 UTC: 	 Log file is /eos/home-c/choij/GenValidation/CMSSW_11_2_0_pre7/src/Configuration/VGenStudies/crab_submit_files/crab_DY_012j_MGNLO_v271/crab.log
